%% experimental_coding_key

key = {'Trial','Time','Block id','Stim 1 p(win)','Stim 2 p(lose)','Stimulus (1=Blue/2=Orange)'...
    ,'Stimulus location on screen (1=BlueLEFT/2=BlueRIGHT)','Player prediction - (Left = 1 VS Right = 0)'...
    ,'RT','Stimulus Outcome (Orange Win=0/Blue Win=1)','WIN vs LOSE (player outcome: Win=1/Lose=0)'...
    ,'Prediction time','ITI','Time for stimulus presenation','Time of RESP outcome'...
    ,'TAPAS resp Model = (1=subj picked Blue/0=subj picked Orange)','fix_time'};
player_struct.experiment_key = key; clear key;

